---
apiVersion: "v2"
name: "grafaml"
description: "Generate Grafana dashboards from YAML with automatic panel positioning using Helm Chart templating."
type: "application"
icon: "https://avatars.githubusercontent.com/u/7195757"
keywords:
  - "grafana"
  - "kubernetes"
  - "helm"
  - "dashboard"
  - "monitoring"
  - "observability"
maintainers:
  - name: "ernail"
    email: "nagel.eric.95@googlemail.com"
annotations:
  artifacthub.io/license: "MIT"
  artifacthub.io/links: |
    - name: source
      url: https://github.com/erNail/grafaml
    - name: support
      url: https://github.com/erNail/grafaml/issues
version: "0.0.0"

# renovate: image=grafana/grafana
appVersion: "12.2.1"
...
