---
name: "Renovate"

"on":
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

jobs:
  renovate-job:
    runs-on: "ubuntu-24.04"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v4.2.2"
      - name: "Run Renovate"
        uses: "renovatebot/github-action@v43.0.20"
        with:
          configurationFile: "./renovate-config.js"
          token: "${{ secrets.RENOVATE_BOT_TOKEN }}"
        env:
          RENOVATE_REPO: "${{ github.repository }}"
